project:
  type: website

website:
  title: "ISSS608-VAA-Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Overview
      - href: userguide.qmd
        text: User Guide
      - href: poster.qmd
        text: Poster
      - href: https://github.com/acapgalano/ISSS608-VAA-ProjectApp
        text: Github
      - about.qmd

format:
  html:
    page-layout: full
    theme: journal
    backgroundcolor: "#fdfcdc"
    css: styles.css
    toc: true
    code-fold: show
    code-overflow: wrap
    code-tools:
      source: true
      toggle: true
      caption: none
    code-summary: "Press to toggle code"
editor: visual
